#========================================================
# vnpip/cnode:stage3 : Run node on Debian stable slim
#========================================================
# FROM vnpip/cnode:stage2 AS build
# FROM cardanocommunity/cardano-node:stage2 AS build

FROM debian:stable-slim

LABEL maintainer="VNPIPS Staking Team (ada.vnpips.com)"

ARG DEBIAN_FRONTEND=noninteractive

ENV \
    ENV=/etc/profile \
    LC_ALL=en_US.UTF-8 \
    LANG=en_US.UTF-8 \
    LANGUAGE=en_US.UTF-8 \
    CNODE_HOME=/opt/cardano/cnode \
    PATH=/nix/var/nix/profiles/per-user/$NONEROOTUSER/profile/bin:/nix/var/nix/profiles/per-user/$NONEROOTUSER/profile/sbin:/opt/cardano/cnode/scripts:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/home/$NONEROOTUSER/.cabal/bin \
    GIT_SSL_CAINFO=/etc/ssl/certs/ca-certificates.crt \
    NIX_SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt \
    NIX_PATH=/nix/var/nix/profiles/per-user/$NONEROOTUSER/channels

USER root
WORKDIR /

# PREREQ --no-install-recommends
RUN apt-get update \
    && apt-get install -y build-essential libffi-dev libffi6 libgmp-dev libgmp10 libncurses-dev libncurses5 libtinfo5 \
    && apt-get install -y libcap2-bin ncurses-bin iproute2 curl wget apt-utils xz-utils netbase sudo coreutils dnsutils net-tools procps tcptraceroute bc \
    && apt-get install -y telnet telnetd netcat nano zip unzip htop nload nmap iputils-ping iptables \
    && apt-get install -y --no-install-recommends cron \
    && sudo apt-get -y purge && sudo apt-get -y clean && sudo apt-get -y autoremove && sudo rm -rf /var/lib/apt/lists/* # && sudo rm -rf /usr/bin/apt*
    
# Install locales package
RUN  apt-get update && apt-get install --no-install-recommends -y locales

# Install ghcup package
# RUN  curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh

#  en_US.UTF-8 for inclusion in generation
RUN sed -i 's/^# *\(en_US.UTF-8\)/\1/' /etc/locale.gen \
    && locale-gen \
    && echo "export LC_ALL=en_US.UTF-8" >> ~/.bashrc \
    && echo "export LANG=en_US.UTF-8" >> ~/.bashrc \
    && echo "export LANGUAGE=en_US.UTF-8" >> ~/.bashrc


# SETUP NONEROOTUSER
ARG NONEROOTUSER=vnpip

RUN adduser --disabled-password --gecos '' $NONEROOTUSER \
    && echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers \
    && adduser $NONEROOTUSER sudo \
    && chown -R $NONEROOTUSER:$NONEROOTUSER /home/$NONEROOTUSER/.*

# Run non-privileged command
USER $NONEROOTUSER
WORKDIR /home/$NONEROOTUSER

ENV \
    ENV=/etc/profile \
    LC_ALL=en_US.UTF-8 \
    LANG=en_US.UTF-8 \
    LANGUAGE=en_US.UTF-8 \
    CNODE_HOME=/opt/cardano/cnode \
    LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH" \
    PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH" \
    CARDANO_NODE_SOCKET_PATH="$CNODE_HOME/sockets/node0.socket" \
    PATH=/home/$NONEROOTUSER/.local/bin:/nix/var/nix/profiles/per-user/$NONEROOTUSER/profile/bin:/nix/var/nix/profiles/per-user/$NONEROOTUSER/profile/sbin:/opt/cardano/cnode/scripts:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/home/$NONEROOTUSER/.cabal/bin \
    GIT_SSL_CAINFO=/etc/ssl/certs/ca-certificates.crt \
    NIX_SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt \
    NIX_PATH=/nix/var/nix/profiles/per-user/$NONEROOTUSER/channels

RUN mkdir -p /home/$NONEROOTUSER/.cabal/bin

# COPY NODE BINS AND DEPS 
COPY --from=vnpip/cnode:stage2 /root/.cabal/bin/* /home/$NONEROOTUSER/.cabal/bin/
COPY --from=vnpip/cnode:stage2 /lib/x86_64-linux-gnu/lib* /lib/x86_64-linux-gnu/
COPY --from=vnpip/cnode:stage2 /lib64/ld-linux-x86-64* /lib64/
COPY --from=vnpip/cnode:stage2 /usr/lib/x86_64-linux-gnu/libgmp.* /usr/lib/x86_64-linux-gnu/
COPY --from=vnpip/cnode:stage2 /usr/lib/x86_64-linux-gnu/liblz4.* /usr/lib/x86_64-linux-gnu/
COPY --from=vnpip/cnode:stage2 /usr/lib/x86_64-linux-gnu/libsodium.* /usr/lib/x86_64-linux-gnu/
COPY --from=vnpip/cnode:stage2 /opt/ /opt/

RUN sudo chmod a+x /home/$NONEROOTUSER/.cabal/bin/* && ls /opt/ 

# Setup running cron job
# -- Add crontab file in the cron directory
ADD addfile/crontab /etc/cron.d/crontab
# -- Give execution rights on the cron job
RUN sudo chmod 0644 /etc/cron.d/crontab \
    && crontab /etc/cron.d/crontab
# -- Create the log file to be able to run tail
RUN sudo touch /var/log/cron.log

RUN cd /usr/bin \
&& sudo wget http://www.vdberg.org/~richard/tcpping \
&& sudo chmod 755 tcpping

# INSTALL NIX
RUN sudo curl -sL https://nixos.org/nix/install | sh \
    && sudo ln -s /nix/var/nix/profiles/per-user/etc/profile.d/nix.sh /etc/profile.d/ \
    && . /home/$NONEROOTUSER/.nix-profile/etc/profile.d/nix.sh \
    && sudo crontab -u $NONEROOTUSER /etc/cron.d/crontab \
    && echo "alias cntools=$CNODE_HOME/scripts/cntools.sh" >> ~/.bashrc \
    && echo "alias gLiveView=$CNODE_HOME/scripts/gLiveView.sh" >> ~/.bashrc \
    && echo "alias nodestart=/home/$NONEROOTUSER/.scripts/start_all.sh" >> ~/.bashrc \
    && echo "alias nodestop=/home/$NONEROOTUSER/.scripts/stop_all.sh" >> ~/.bashrc \
    && echo "alias cleancaches=/home/$NONEROOTUSER/.scripts/cleanCaches.sh" >> ~/.bashrc \
    && echo "alias clearlogs=/home/$NONEROOTUSER/.scripts/clearlogs.sh" >> ~/.bashrc \
    && echo "alias memory_alert=/home/$NONEROOTUSER/.scripts/memory_alert.sh" >> ~/.bashrc \
    && echo "alias peerIN_check=/home/$NONEROOTUSER/.scripts/peerIN_check.sh" >> ~/.bashrc \
    && echo "alias getDataDrive=/home/$NONEROOTUSER/.scripts/getDataDrive.sh" >> ~/.bashrc \
    && echo "alias poolstatsUpdater=/home/$NONEROOTUSER/.scripts/poolstatsUpdater.sh" >> ~/.bashrc \
    && echo "export PATH=/nix/var/nix/profiles/per-user/$NONEROOTUSER/profile/bin:/nix/var/nix/profiles/per-user/$NONEROOTUSER/profile/sbin:/opt/cardano/cnode/scripts:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/home/$NONEROOTUSER/.cabal/bin"  >> ~/.bashrc

# INSTALL DEPS  
RUN /nix/var/nix/profiles/per-user/$NONEROOTUSER/profile/bin/nix-env -i python3 systemd libsodium tmux jq ncurses libtool autoconf git wget gnupg column less openssl vim \
    && /nix/var/nix/profiles/per-user/$NONEROOTUSER/profile/bin/nix-channel --update \
    && /nix/var/nix/profiles/per-user/$NONEROOTUSER/profile/bin/nix-env -u --always \
    && /nix/var/nix/profiles/per-user/$NONEROOTUSER/profile/bin/nix-collect-garbage -d \
    && sudo rm /nix/var/nix/profiles/per-user/$NONEROOTUSER/profile/bin/nix-*

# Install Prometheus Node Exporter
#ADD addfile/node-exporter-latest.txt ./
#RUN NEVERSION=$(cat node-exporter-latest.txt) \
#  && DIRNAME="node_exporter-$NEVERSION.linux-amd64" \
#  && wget https://github.com/prometheus/node_exporter/releases/download/v$NEVERSION/$DIRNAME.tar.gz \
#  && tar xvfz $DIRNAME.tar.gz \
#  && sudo mv $DIRNAME/node_exporter /usr/local/bin/ \
#  && rm -rf $DIRNAME.tar.gz \
#  && rm -rf $DIRNAME

# ADD SCRIPT
ADD addfile/banner.txt /home/$NONEROOTUSER/.scripts/
ADD addfile/getDataDrive.sh /home/$NONEROOTUSER/.scripts/
ADD addfile/start_all.sh /home/$NONEROOTUSER/.scripts/
ADD addfile/stop_all.sh /home/$NONEROOTUSER/.scripts/
ADD addfile/cleanCaches.sh /home/$NONEROOTUSER/.scripts/
ADD addfile/clearlogs.sh /home/$NONEROOTUSER/.scripts/
ADD addfile/memory_alert.sh /home/$NONEROOTUSER/.scripts/
ADD addfile/peerIN_check.sh /home/$NONEROOTUSER/.scripts/
ADD addfile/poolstatsUpdater.sh /home/$NONEROOTUSER/.scripts/
ADD addfile/sendmytip.sh /home/$NONEROOTUSER/.scripts/
ADD addfile/entrypoint.sh ./

RUN sudo chown -R $NONEROOTUSER:$NONEROOTUSER $CNODE_HOME/* \
    && sudo chown -R $NONEROOTUSER:$NONEROOTUSER /home/$NONEROOTUSER/.* \
    && sudo chmod a+x /home/$NONEROOTUSER/.scripts/*.sh /home/$NONEROOTUSER/entrypoint.sh

# UPDATE DB
#RUN cd /opt/cardano/cnode \
#    && sudo /home/$NONEROOTUSER/.scripts/getDataDrive.sh 1O_vA-_AgYpgpN5JVBrhLsFiN6LajLYzF db.zip \
#    && unzip db.zip \
#    && sudo rm -rf db.zip

# Expose NODE_PORT & EKG-prometheus monitoring ports
EXPOSE 6000 12798 
# Expose Node Exporter 
# EXPOSE 9100

ENTRYPOINT ["./entrypoint.sh"]
