global:
  scrape_interval: 15s
  external_labels:
    monitor: "codelab-monitor"

scrape_configs:
  - job_name: "relay" # To scrape data from the cardano relay node
    scrape_interval: 5s
    static_configs:
      - targets: ["127.0.0.1:12798"]
  - job_name: "staking" # To scrape data from the cardano staking node
    scrape_interval: 5s
    static_configs:
      - targets: ["127.0.0.1:12799"]
